import React, { useState, useEffect } from "react";
import { connect } from "react-redux";
import PropTypes from "prop-types";

import CourseForm from "./CourseForm";
import { newCourse } from "../../../tools/mockData";
import { loadCourses, saveCourse } from "../../redux/actions/courseActions";
import { loadAuthors } from "../../redux/actions/authorActions";

function ManageCoursePage({
  courses,
  authors,
  loadCourses,
  loadAuthors,
  saveCourse,
  history, // Auto generated by react router Route
  ...props
}) {
  const [course, setCourse] = useState({ ...props.course });
  const [errors, setErrors] = useState({});

  // Handle change
  const handleChange = event => {
    const { name, value } = event.target;
    setCourse(prevState => ({
      ...prevState,
      [name]: value
    }));
  };

  // Handle save
  const handleSave = event => {
    event.preventDefault();
    saveCourse(course).then(() => history.push("./courses"));
  };

  useEffect(() => {
    if (courses.length == 0) {
      loadCourses().catch(error => {
        alert("Loading courses failed (" + error + ")");
      });
    }

    if (authors.length == 0) {
      loadAuthors().catch(error => {
        alert("Loading authors failed (" + error + ")");
      });
    }
  }, []);

  return (
    <>
      <CourseForm
        course={course}
        authors={authors}
        errors={errors}
        onSave={handleSave}
        onChange={handleChange}
      ></CourseForm>
    </>
  );
}

ManageCoursePage.propTypes = {
  course: PropTypes.object.isRequired,
  courses: PropTypes.array.isRequired,
  authors: PropTypes.array.isRequired,
  loadCourses: PropTypes.func.isRequired,
  loadAuthors: PropTypes.func.isRequired,
  saveCourse: PropTypes.func.isRequired,
  history: PropTypes.object.isRequired
};

const mapStateToProps = state => {
  return {
    course: newCourse,
    courses: state.courses,
    authors: state.authors
  };
};

/* const mapDispatchToProps = dispatch => {
  return {
    actions: {
      loadCourses: bindActionCreators(courseActions.loadCourses, dispatch),
      loadAuthors: bindActionCreators(authorActions.loadAuthors, dispatch)
    }
  };
}; */

const mapDispatchToProps = {
  loadCourses,
  loadAuthors,
  saveCourse
};

export default connect(mapStateToProps, mapDispatchToProps)(ManageCoursePage);
